import { Assets } from 'react-native-ui-lib';

Assets.loadAssetsGroup('icons', {
    gallery: require('assets/icon/gallery.png'),
    camera: require('assets/icon/camera.png'),
    add: require('assets/icon/add.png'),
    back: require('assets/icon/back.png'),
    notifycation: require('assets/icon/bell.png'),
    chat: require('assets/icon/chat.png'),
    cancel: require('assets/icon/cancel.png'),
    comment: require('assets/icon/comment.png'),
    diaphragm: require('assets/icon/diaphragm.png'),
    dots: require('assets/icon/dots.png'),
    flag: require('assets/icon/finish.png'),
    fork: require('assets/icon/fork.png'),
    fire: require('assets/icon/fire.png'),
    Profile: require('assets/icon/user.png'),
    Home: require('assets/icon/home.png'),
    library: require('assets/icon/library.png'),
    location: require('assets/icon/location.png'),
    more: require('assets/icon/more.png'),
    fire_black: require('assets/icon/passion.png'),
    play_button: require('assets/icon/play_button.png'),
    plus: require('assets/icon/plus.png'),
    search: require('assets/icon/search.png'),
    edit: require('assets/icon/edit.png'),
    report: require('assets/icon/report.png'),
    google: require('assets/icon/google.png'),
    send: require('assets/icon/send.png'),
    plus_only: require('assets/icon/plus_only.png'),
    line: require('assets/icon/line.png'),
    Settings: require('assets/icon/settings.png'),
    arrow_back: require('assets/icon/arrow_back.png'),
    arrow_down: require('assets/icon/down_arrow.png'),
    gps: require('assets/icon/gps.png'),
    clock: require('assets/icon/clock.png'),
    flash: require('assets/icon/flash.png'),
    un_flash: require('assets/icon/Un_flash.png'),
    switch_camera: require('assets/icon/switch_camera.png'),
    tickCamera: require('assets/icon/tickCamera.png'),
    crop: require('assets/icon/crop.png'),
    languages:require('assets/icon/languages.png'),
    right_arrow:require('assets/icon/right_arrow.png'),
    protection:require('assets/icon/protection.png'),
    notes:require('assets/icon/notes.png'),
    unhappy:require('assets/icon/unhappy.png'),
    log_out:require('assets/icon/log_out.png'),
    vietnam: require('assets/icon/vietnam.png'),
    france: require('assets/icon/france.png'),
    english: require('assets/icon/english.png'),
    china: require('assets/icon/china.png'),
    japan: require('assets/icon/japan.png'),
    logoapp: require('assets/icon/logo.png'),
    starving: require('assets/gif/starving.gif'),
    history: require('assets/icon/history.png'),
    core: require('assets/icon/core.png'),
    pause_button: require('assets/icon/pause_button.png'),
    check_follow: require('assets/icon/check_follow.png'),
    cancle_follow:require('assets/icon/cancle_follow.png'),
    check: require('assets/icon/check-mark.png'),
    intermittent: require('assets/gif/intermittent.gif'),
    dont: require('assets/gif/dont.gif'),
    done: require('assets/gif/done.gif'),
    warning: require('assets/gif/warning.gif'),
    empty: require('assets/icon/empty.png'),
    share: require('assets/icon/share.png'),
    bookmark: require('assets/icon/bookmark.png'),
    retweet: require('assets/icon/retweet.png'),
    send_white: require('assets/icon/send_white.png'),
    recomment: require('assets/icon/recomment.png'),
    wallet: require('assets/icon/wallet.png'),
    link: require('assets/icon/link.png'),
    insurance: require('assets/icon/insurance.png'),
    question: require('assets/icon/question.png'),
    info: require('assets/icon/info.png'),
    follow: require('assets/icon/follow.png'),
    remove: require('assets/icon/remove.png'),
    dot: require('assets/icon/dot.png'),
    toggle_off: require('assets/icon/toggle_off.png'),
    toggle_on: require('assets/icon/toggle_on.png'),
    send_message: require('assets/icon/send_message.png'),
    brush: require('assets/icon/brush.png'),
    dice: require('assets/icon/dice.png'),
    mailing: require('assets/icon/mailing.png'),
    advertisement: require('assets/icon/advertisement.png'),
    messenger: require('assets/icon/messenger.png'),
    bot: require('assets/icon/robot.png'),
    un_bot: require('assets/icon/un_robot.png'),
})