import { Assets } from 'react-native-ui-lib';

Assets.loadAssetsGroup('icons', {
    gallery: require('assets/icon/gallery.png'),
    camera: require('assets/icon/camera.png'),
    add: require('assets/icon/add.png'),
    back: require('assets/icon/back.png'),
    notifycation: require('assets/icon/bell.png'),
    cancel: require('assets/icon/cancel.png'),
    comment: require('assets/icon/comment.png'),
    diaphragm: require('assets/icon/diaphragm.png'),
    dots: require('assets/icon/dots.png'),
    flag: require('assets/icon/finish.png'),
    fork: require('assets/icon/fork.png'),
    fire: require('assets/icon/home.png'),
    library: require('assets/icon/library.png'),
    location: require('assets/icon/location.png'),
    more: require('assets/icon/more.png'),
    fire_black: require('assets/icon/passion.png'),
    play_button: require('assets/icon/play_button.png'),
    plus: require('assets/icon/plus.png'),
    search: require('assets/icon/search.png'),
    edit: require('assets/icon/edit.png'),
    chopsticks: require('assets/icon/chopsticks.png'),
    google: require('assets/icon/google.png'),
    send: require('assets/icon/send.png'),
    plus_only: require('assets/icon/plus_only.png'),
    line: require('assets/icon/line.png'),
    settings: require('assets/icon/settings.png'),
    arrow_back: require('assets/icon/arrow_back.png'),
    arrow_down: require('assets/icon/down_arrow.png'),
    gps: require('assets/icon/gps.png'),
    clock: require('assets/icon/clock.png'),
    flash: require('assets/icon/flash.png'),
    un_flash: require('assets/icon/Un_flash.png'),
    switch_camera: require('assets/icon/switch_camera.png'),
    tickCamera: require('assets/icon/tickCamera.png'),
    crop: require('assets/icon/crop.png'),
    languages:require('assets/icon/languages.png'),
    right_arrow:require('assets/icon/right_arrow.png'),
    protection:require('assets/icon/protection.png'),
    notes:require('assets/icon/notes.png'),
    unhappy:require('assets/icon/unhappy.png'),
    log_out:require('assets/icon/log_out.png'),
    warning: require('assets/icon/warning.png'),
    vietnam: require('assets/icon/vietnam.png'),
    france: require('assets/icon/france.png'),
    english: require('assets/icon/english.png'),
    china: require('assets/icon/china.png'),
    japan: require('assets/icon/japan.png'),
    logoapp: require('assets/icon/logo.png'),
    logoapp2: require('assets/icon/logoapp2.png'),
    logoapp3: require('assets/icon/logoapp3.png'),
})